### PR TITLE
Temporary commit for Arm

### PR DESCRIPTION
**Pull request by hairygael**
This is a temporary commit to show how the ARM UI is set up.

### CODE REVIEW

**Comment by supertick** [comment]
what is a temporary commit ? what am I supposed to do with this Gael ?

**Comment by hairygael** [comment]
I never tried draft commits on github, but it seemed to be appropriate for
a commit that is only meant to be temporary.
Because I have modified the main background image for you to see how the
buttons (rectangle) are placed and what is the purpose of the re blinking
light.
I think it should be merged to save the files and code and I won't leave it
long that way to avoid people downloading that version.

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>

**Comment by supertick** [comment]
image
I cannot merge it - "Draft pull requests cannot be merged"

**Comment by hairygael** [comment]
Ah ok, I will see what can be done.
Thanks Greg

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>

**Pull request merged**
